from .production_env_guards import apply_production_env_guards as _apply_production_env_guards

_apply_production_env_guards()

from .kpi_semantics import install_kpi_semantics_guard as _install_kpi_semantics_guard
_install_kpi_semantics_guard()

from .one_time_token_safety import install_one_time_token_safety as _install_one_time_token_safety
_install_one_time_token_safety()

from .capability_retention import install_capability_retention as _install_capability_retention
_install_capability_retention()

from .oauth_state_safety import install_oauth_state_safety as _install_oauth_state_safety
_install_oauth_state_safety()

from .queue_claim_safety import install_queue_claim_safety as _install_queue_claim_safety
_install_queue_claim_safety()

from .job_error_safety import install_job_error_safety as _install_job_error_safety
_install_job_error_safety()

from .execution_log_safety import install_execution_log_safety as _install_execution_log_safety
_install_execution_log_safety()

from .email_outbox_privacy import install_email_outbox_privacy as _install_email_outbox_privacy
_install_email_outbox_privacy()

from .workspace_billing_defaults import install_workspace_billing_defaults as _install_workspace_billing_defaults
_install_workspace_billing_defaults()

from .billing_event_minimization import install_billing_event_minimization as _install_billing_event_minimization
_install_billing_event_minimization()

# Bound signed Stripe event identifiers before app.main binds parse_webhook.
from .stripe_event_safety import install_stripe_event_safety as _install_stripe_event_safety
_install_stripe_event_safety()

from .google_read_reliability import install_google_read_reliability as _install_google_read_reliability
_install_google_read_reliability()

from .meta_read_reliability import install_meta_read_reliability as _install_meta_read_reliability
_install_meta_read_reliability()

from . import google_ads_diagnostics as _google_ads_diagnostics
from . import connector_empty_states as _connector_empty_states
from . import connector_privacy_controls as _connector_privacy_controls
from . import account_privacy_controls as _account_privacy_controls
from . import beta_readiness as _beta_readiness
from .cron_auth_safety import install_cron_auth_safety as _install_cron_auth_safety
from .csrf_guard import install_csrf_guard as _install_csrf_guard
from .http_error_safety import install_http_error_safety as _install_http_error_safety
from .main import app as _app
from .oauth_callback_guard import install_oauth_callback_guard as _install_oauth_callback_guard
from .production_docs_guard import install_production_docs_guard as _install_production_docs_guard
from .production_execution_guard import install_production_execution_guard as _install_production_execution_guard
from .production_token_response_guard import install_production_token_response_guard as _install_production_token_response_guard
from .public_health import install_public_health_guard as _install_public_health_guard
from .public_routing import install_public_routing as _install_public_routing
from .runtime_diagnostics import install_runtime_diagnostics as _install_runtime_diagnostics
from .security_headers import install_security_headers as _install_security_headers
from .static_entrypoint_guard import install_static_entrypoint_guard as _install_static_entrypoint_guard

_install_cron_auth_safety()
_install_http_error_safety(_app)
_install_security_headers(_app)
_install_csrf_guard(_app)
_install_public_health_guard(_app)
_install_runtime_diagnostics(_app)
_install_static_entrypoint_guard(_app)
_install_production_docs_guard(_app)
_install_production_execution_guard(_app)
_install_oauth_callback_guard(_app)
_install_production_token_response_guard(_app)
_install_public_routing(_app)

__all__ = []
